apiVersion: apps/v1
kind: Deployment
metadata:
  name: johndoe-deployment
  labels:
    app: johndoe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: johndoe
  template:
    metadata:
      labels:
        app: johndoe
    spec:
      containers:
      - name: johndoe
        image: nginx:latest
        ports:
        - containerPort: 80
